"""Generate and append offline quotes with real authors to quote files."""
from pathlib import Path
import random

OUT_DIR = Path(__file__).resolve().parents[1]

# Real quotes with authors for each theme
QUOTES_EN = {
    'life': [
        '"Life is what happens to you while you\'re busy making other plans." — John Lennon',
        '"The purpose of our lives is to be happy." — Dalai Lama',
        '"Get busy living or get busy dying." — Stephen King',
        '"The way to get started is to quit talking and begin doing." — Walt Disney',
        '"Don\'t let yesterday take up too much of today." — Will Rogers',
        '"You learn more from failure than from success." — Unknown',
        '"It\'s not whether you get knocked down, it\'s whether you get up." — Vince Lombardi',
        '"If you are working on something that you really care about, you don\'t have to be pushed. The vision pulls you." — Steve Jobs',
        '"People who are crazy enough to think they can change the world, are the ones who do." — Rob Siltanen',
        '"Failure will never overtake me if my determination to succeed is strong enough." — Og Mandino',
        '"We may encounter many defeats but we must not be defeated." — Maya Angelou',
        '"Knowing is not enough; we must apply. Wishing is not enough; we must do." — Johann Wolfgang Von Goethe',
        '"The only impossible journey is the one you never begin." — Tony Robbins',
        '"In the end, we will remember not the words of our enemies, but the silence of our friends." — Martin Luther King Jr',
        '"Do something today that your future self will thank you for." — Sean Patrick Flanery',
        '"Little things make big days." — Unknown',
        '"It\'s going to be hard, but hard does not mean impossible." — Unknown',
        '"Don\'t wait for opportunity. Create it." — Unknown',
        '"Sometimes we\'re tested not to show our weaknesses, but to discover our strengths." — Unknown',
        '"The key to success is to focus on goals, not obstacles." — Unknown',
        '"Your limitation—it\'s only your imagination." — Unknown',
        '"Great things never come from comfort zones." — Unknown',
        '"Dream it. Wish it. Do it." — Unknown',
        '"Success doesn\'t just find you. You have to go out and get it." — Unknown',
        '"The harder you work for something, the greater you\'ll feel when you achieve it." — Unknown',
        '"Dream bigger. Do bigger." — Unknown',
        '"Don\'t stop when you\'re tired. Stop when you\'re done." — Unknown',
        '"Wake up with determination. Go to bed with satisfaction." — Unknown',
        '"Do something now; your future self will love you for it." — Sean Patrick Flanery',
        '"Little progress each day is big progress." — Unknown',
        '"Don\'t watch the clock; do what it does. Keep going." — Sam Levenson',
        '"The future depends on what you do today." — Mahatma Gandhi',
        '"Believe you can and you\'re halfway there." — Theodore Roosevelt',
        '"When you have a dream, you\'ve got to grab it and never let go." — Carol Carter',
        '"I have learned over the years that when one\'s mind is made up, this diminishes fear; knowing what must be done does away with fear." — Rosa Parks',
        '"Nothing is impossible. The word itself says I\'m possible!" — Audrey Hepburn',
        '"There is nothing impossible to they who will try." — Alexander the Great',
        '"The only limit to our realization of tomorrow will be our doubts of today." — Franklin D. Roosevelt',
        '"Do what you feel in your heart to be right." — Eleanor Roosevelt',
        '"Whether you think you can, or you think you can\'t—you\'re right." — Henry Ford',
    ],
    'love': [
        '"The heart has its reasons which reason knows nothing of." — Blaise Pascal',
        '"Love is composed of a single soul inhabiting two bodies." — Aristotle',
        '"If you love deeply, you\'re going to get hurt badly. But this is the price you pay for a rich and full life." — Bill Clinton',
        '"There is no remedy for love but to love more." — Henry David Thoreau',
        '"Love all, trust a few, do wrong to none." — William Shakespeare',
        '"The greatest thing you\'ll ever learn is just to love and be loved in return." — Moulin Rouge',
        '"Love is like the wind, you can\'t see it but you can feel it." — Nicholas Sparks',
        '"Love is a game that two can play and both win." — Eva Gabor',
        '"When you fall in love, it is a temporary madness." — Louis de Bernieres',
        '"To love is to risk not being loved in return." — Julia Roberts',
        '"Love doesn\'t make the world go round. Love is what makes the ride worthwhile." — Franklin P. Jones',
        '"We accept the love we think we deserve." — Stephen Chbosky',
        '"Love is the only force capable of transforming an enemy into friend." — Martin Luther King Jr',
        '"The best and most beautiful things in this world cannot be seen or even heard, but must be felt with the heart." — Helen Keller',
        '"Love never fails." — 1 Corinthians 13:8',
        '"I love you without knowing how, or when, or from where." — Pablo Neruda',
        '"For every moment you are angry you lose sixty seconds of happiness." — Ralph Waldo Emerson',
        '"Love is the bridge between you and everything." — Rumi',
        '"Love is life. All, everything that I understand, I understand only because I love." — Leo Tolstoy',
        '"At the end of the day, it\'s not about what you have or even what you\'ve accomplished. It\'s about who you\'ve loved and how much." — Unknown',
        '"You are my greatest adventure." — Unknown',
        '"I love you more than words can say." — Unknown',
        '"Love is when two hearts become one heart." — Unknown',
        '"The love between us is forever growing." — Unknown',
        '"You are my person." — Unknown',
        '"All you need is love." — The Beatles',
        '"I would find you in any life." — Unknown',
        '"Love is a flower that blooms in the heart." — Unknown',
        '"You make my heart smile." — Unknown',
        '"Love is not about finding the perfect person, but about seeing an imperfect person perfectly." — Sam Keen',
        '"I fell in love the way you fall asleep: slowly, then all at once." — John Green',
        '"Love is patient, love is kind." — 1 Corinthians 13:4',
        '"Love is the only thing that we can carry with us when we die." — Louisa May Alcott',
        '"The opposite of love is not hate, but indifference." — Elie Wiesel',
        '"To love oneself is the beginning of a lifelong romance." — Oscar Wilde',
        '"Love is the most beautiful of all the emotions. Even heartbreak is beautiful." — Unknown',
        '"I choose you. And I\'ll choose you over and over and over. Without pause, without doubt, in a heartbeat. I\'ll keep choosing you." — Unknown',
    ],
    'motivation': [
        '"Don\'t watch the clock; do what it does. Keep going." — Sam Levenson',
        '"The only way to do great work is to love what you do." — Steve Jobs',
        '"Innovation distinguishes between a leader and a follower." — Steve Jobs',
        '"Life is either a daring adventure or nothing at all." — Helen Keller',
        '"The future belongs to those who believe in the beauty of their dreams." — Eleanor Roosevelt',
        '"It is during our darkest moments that we must focus to see the light." — Aristotle',
        '"The only impossible journey is the one you never begin." — Tony Robbins',
        '"Success is not final, failure is not fatal: it is the courage to continue that counts." — Winston Churchill',
        '"Believe you can and you\'re halfway there." — Theodore Roosevelt',
        '"The best time to plant a tree was 20 years ago. The second best time is now." — Chinese Proverb',
        '"Your time is limited, so don\'t waste it living someone else\'s life." — Steve Jobs',
        '"The only person you are destined to become is the person you decide to be." — Ralph Waldo Emerson',
        '"Don\'t let yesterday take up too much of today." — Will Rogers',
        '"You miss 100% of the shots you don\'t take." — Wayne Gretzky',
        '"Whether you think you can, or you think you can\'t—you\'re right." — Henry Ford',
        '"I learned that courage was not the absence of fear, but the triumph over it." — Nelson Mandela',
        '"The only way to achieve the impossible is to believe it is possible." — Charles Kingsleigh',
        '"Success is not how high you have climbed, but how you make people feel when you\'re standing next to them." — Zig Ziglar',
        '"Do what you feel in your heart to be right." — Eleanor Roosevelt',
        '"The only limit to our realization of tomorrow will be our doubts of today." — Franklin D. Roosevelt',
        '"What we fear doing most is usually what we most need to do." — Tim Ferriss',
        '"Don\'t wait for opportunity. Create it." — Unknown',
        '"Motivation comes from working on things we care about." — Unknown',
        '"The pain you feel today will be the strength you feel tomorrow." — Unknown',
        '"You don\'t have to see the whole staircase, just take the first step." — Martin Luther King Jr',
        '"Act as if what you do makes a difference. It does." — William James',
        '"Success is walking from failure to failure with no loss of enthusiasm." — Winston Churchill',
        '"The successful warrior is the average man, with laser-like focus." — Bruce Lee',
        '"Excellence is not a destination; it is a continuous journey that never ends." — Brian Tracy',
        '"Don\'t quit. Suffer now and live the rest of your life as a champion." — Muhammad Ali',
        '"Your only limit is your soul." — Unknown',
        '"Keep your eyes on the prize." — Unknown',
        '"Strength doesn\'t come from what you can do. It comes from overcoming the things you once thought you couldn\'t." — Rikki Rogers',
        '"Dream it. Wish it. Do it." — Unknown',
        '"Success doesn\'t just find you. You have to go out and get it." — Unknown',
        '"The harder you work for something, the greater you\'ll feel when you achieve it." — Unknown',
    ],
    'wisdom': [
        '"The only true wisdom is in knowing you know nothing." — Socrates',
        '"In the middle of difficulty lies opportunity." — Albert Einstein',
        '"The only thing we have to fear is fear itself." — Franklin D. Roosevelt',
        '"An examined life is not worth living." — Socrates',
        '"Knowing yourself is the beginning of all wisdom." — Aristotle',
        '"The greatest glory in living lies not in never falling, but in rising every time we fall." — Nelson Mandela',
        '"Wisdom is the supreme part of happiness." — Sophocles',
        '"To keep the body in good health is a duty... otherwise we shall not be able to keep our mind strong and clear." — Buddha',
        '"The only way to deal with an unfree world is to become so absolutely free that very existence is an act of rebellion." — Albert Camus',
        '"You cannot teach a person anything; you can only help him find it within himself." — Galileo',
        '"The man of knowledge must be able not only to know what to do, but to refrain from doing." — Confucius',
        '"Wisdom is not the product of schooling but of the lifelong attempt to acquire it." — Albert Einstein',
        '"The wise adapt themselves to circumstances, as water molds itself to the pitcher." — Chinese Proverb',
        '"All that we are is the result of what we have thought. If a man speaks or acts with an evil thought, pain follows him." — Buddha',
        '"A wise man gets more use from his enemies than a fool from his friends." — Baltasar Gracian',
        '"The only true wisdom is admitting your ignorance." — Socrates',
        '"To plant a garden is to believe in tomorrow." — Audrey Hepburn',
        '"Silence is a source of great strength." — Lao Tzu',
        '"Be like water." — Bruce Lee',
        '"The journey of a thousand miles begins with a single step." — Lao Tzu',
        '"Everything we know about wisdom is incomplete." — Socrates',
        '"We cannot live only for ourselves. A thousand fibers connect us with our fellow men; and among those fibers, as sympathetic threads, we feel every quiver." — Herman Melville',
        '"Wisdom is the daughter of experience." — Leonardo da Vinci',
        '"The unexamined life is not worth living." — Socrates',
        '"Words may be deeds." — John Heywood',
        '"Every strike brings me closer to the next home run." — Babe Ruth',
        '"Do not seek to follow in the footsteps of the wise; seek what they sought." — Matsuo Basho',
        '"The more you know, the more you realize you don\'t know." — Unknown',
        '"Accept everything about yourself - I mean everything. You are you and that is the beginning and the end - no apologies, no regrets." — Clark Moustakas',
        '"Your body keeps accurate account of your intentions." — Martha Graham',
        '"It is better to remain silent and be thought a fool than to open one\'s mouth and remove all doubt." — Unknown',
        '"The mind is everything. What you think, you become." — Buddha',
        '"Knowledge speaks, but wisdom listens." — Jimi Hendrix',
        '"He who controls the past controls the future. He who controls the present controls the past." — George Orwell',
        '"In every conceivable manner, the family is link to our past, bridge to our future, and bond to one another." — Alex Haley',
    ],
}

QUOTES_RU = {
    'life': [
        '"Жизнь - это то, что происходит, пока ты занят другими планами." — Джон Леннон',
        '"Цель нашей жизни - быть счастливыми." — Далай-лама',
        '"Начните жить или начните умирать." — Стивен Кинг',
        '"Начни с того, что перестанешь говорить и начнешь делать." — Уолт Дисней',
        '"Не позволяй вчера забирать слишком много времени у сегодня." — Уилл Роджерс',
        '"Ты учишься больше на ошибках, чем на успехах." — Неизвестный',
        '"Неважно, сбросят ли тебя с ног, важно, встанешь ли ты." — Винс Ломбарди',
        '"Если ты работаешь над тем, что действительно любишь, тебя не нужно мотивировать." — Стив Джобс',
        '"Только сумасшедшие верят, что смогут изменить мир - и они это делают." — Роб Сильтанен',
        '"Неудача никогда не настигнет тебя, если твоя решимость добиться успеха достаточно сильна." — Ог Мандино',
        '"Мы можем встретить много поражений, но мы не должны быть побеждены." — Майя Анджелоу',
        '"Знать недостаточно; мы должны применять. Хотеть недостаточно; мы должны делать." — Иоганн Вольфганг фон Гёте',
        '"Единственное невозможное путешествие - это то, которое ты никогда не начинаешь." — Тони Роббинс',
        '"В конце концов, мы помним не слова врагов, а молчание друзей." — Мартин Лютер Кинг младший',
        '"Сделай сегодня то, за что тебя будет благодарен твой будущий я." — Шон Патрик Флэнери',
        '"Маленькие вещи делают большие дни." — Неизвестный',
        '"Будет тяжело, но тяжело - не значит невозможно." — Неизвестный',
        '"Не жди возможности. Создай ее." — Неизвестный',
        '"Иногда мы испытываемся не для того, чтобы показать свои слабости, а чтобы открыть свои силы." — Неизвестный',
        '"Ключ к успеху - сосредоточиться на целях, а не на препятствиях." — Неизвестный',
        '"Твое ограничение - это только твое воображение." — Неизвестный',
        '"Великие вещи никогда не приходят из зоны комфорта." — Неизвестный',
        '"Мечтай больше. Делай больше." — Неизвестный',
        '"Успех не найдет тебя сам. Ты должен выйти и получить его." — Неизвестный',
        '"Чем больше ты работаешь для чего-то, тем большее удовлетворение ты чувствуешь, когда достигаешь этого." — Неизвестный',
        '"Не останавливайся, когда устанешь. Останавливайся, когда закончишь." — Неизвестный',
        '"Просыпайся с решимостью. Ложись спать с удовлетворением." — Неизвестный',
        '"Сделай что-нибудь сейчас; твой будущий я поблагодарит тебя." — Шон Патрик Флэнери',
        '"Маленький прогресс каждый день - это большой прогресс." — Неизвестный',
        '"Не смотри на часы; делай то, что они делают. Продолжай идти." — Сэм Левенсон',
        '"Будущее зависит от того, что ты делаешь сегодня." — Махатма Ганди',
        '"Верь, что сможешь - и ты уже половину пути." — Теодор Рузвельт',
        '"Когда у тебя есть мечта, ты должен схватить ее и никогда не отпускать." — Кэрол Картер',
        '"Я понял, что когда ум решен, это уменьшает страх; знание того, что необходимо сделать, избавляет от страха." — Роза Паркс',
        '"Ничего невозможного нет. Само слово говорит: я возможна!" — Одри Хепберн',
        '"Нет ничего невозможного для тех, кто захочет попробовать." — Александр Македонский',
        '"Единственное ограничение нашего понимания завтра - это сомнения в сегодня." — Франклин Д. Рузвельт',
        '"Делай то, что подсказывает твое сердце." — Элеонора Рузвельт',
        '"Думаешь ли ты, что можешь, или думаешь, что не можешь - ты прав." — Генри Форд',
    ],
    'love': [
        '"Сердце имеет свои причины, которые разум не знает." — Блез Паскаль',
        '"Любовь - это одна душа, обитающая в двух телах." — Аристотель',
        '"Если любишь глубоко, получишь сильную боль. Но это цена за богатую и полную жизнь." — Билл Клинтон',
        '"Лекарства от любви нет, кроме как любить еще больше." — Генри Дэвид Торо',
        '"Люби всех, доверяй немногим, никому не делай зла." — Уильям Шекспир',
        '"Величайшее, что ты когда-либо выучишь - просто любить и быть любимым в ответ." — Мулен Руж',
        '"Любовь как ветер - не видишь, но чувствуешь." — Николас Спаркс',
        '"Любовь - это игра, в которую двое могут играть и оба выигрывать." — Ева Габор',
        '"Влюбляясь, ты впадаешь во временное безумие." — Луис де Берньер',
        '"Любить - значит рисковать не быть любимым в ответ." — Джулия Робертс',
        '"Любовь не заставляет мир крутиться. Любовь делает поездку стоящей." — Франклин П. Джонс',
        '"Мы принимаем ту любовь, которую, по нашему мнению, мы заслуживаем." — Стивен Чбоски',
        '"Любовь - единственная сила, способная превратить врага в друга." — Мартин Лютер Кинг младший',
        '"Самое прекрасное в этом мире невозможно увидеть или услышать, можно только чувствовать сердцем." — Хелен Келлер',
        '"Любовь никогда не подводит." — 1 Коринфянам 13:8',
        '"Я люблю тебя, не зная как, когда и откуда." — Пабло Неруда',
        '"За каждый момент, когда ты в гневе, ты теряешь 60 секунд счастья." — Ральф Уолдо Эмерсон',
        '"Любовь - мост между тобой и всем." — Руми',
        '"Любовь - это жизнь. Всё, что я понимаю, я понимаю только потому, что люблю." — Лев Толстой',
        '"В конце концов, дело не в том, что у тебя есть или чего ты достиг. Дело в том, кого ты любил и как сильно." — Неизвестный',
        '"Ты мое величайшее приключение." — Неизвестный',
        '"Я люблю тебя больше, чем слова могут выразить." — Неизвестный',
        '"Любовь - это когда два сердца становятся одним." — Неизвестный',
        '"Любовь между нами все время растет." — Неизвестный',
        '"Ты мой человек." — Неизвестный',
        '"Все, что нужно - это любовь." — The Beatles',
        '"Я нашла бы тебя в любой жизни." — Неизвестный',
        '"Любовь - это цветок, который расцветает в сердце." — Неизвестный',
        '"Ты делаешь мое сердце счастливым." — Неизвестный',
        '"Любовь - это не нахождение идеального человека, а видение несовершенного человека совершенным." — Сэм Кин',
        '"Я влюбилась так, как засыпаешь: медленно, а потом сразу." — Джон Грин',
        '"Любовь терпелива, любовь добра." — 1 Коринфянам 13:4',
        '"Любовь - единственное, что мы можем взять с собой, когда умираем." — Луиза Мэй Олкотт',
        '"Противоположность любви - не ненависть, а равнодушие." — Эли Визель',
        '"Любить себя - начало пожизненного романа." — Оскар Уайльд',
        '"Любовь - самая красивая из всех эмоций. Даже разбитое сердце красиво." — Неизвестный',
    ],
    'motivation': [
        '"Не смотри на часы; делай то, что они делают. Продолжай идти." — Сэм Левенсон',
        '"Единственный способ хорошо работать - любить то, что ты делаешь." — Стив Джобс',
        '"Инновации отличают лидера от последователя." — Стив Джобс',
        '"Жизнь - либо дерзкое приключение, либо ничего." — Хелен Келлер',
        '"Будущее принадлежит тем, кто верит в красоту своих мечтаний." — Элеонора Рузвельт',
        '"В самые темные моменты нужно сосредоточиться, чтобы увидеть свет." — Аристотель',
        '"Единственное невозможное путешествие - то, которое ты никогда не начинаешь." — Тони Роббинс',
        '"Успех не финален, поражение не фатально: важна смелость продолжать." — Уинстон Черчилль',
        '"Верь, что сможешь - и ты уже половину пути." — Теодор Рузвельт',
        '"Лучшее время посадить дерево было 20 лет назад. Второе лучшее время - сейчас." — Китайская пословица',
        '"Твое время ограничено, не трать его на чужую жизнь." — Стив Джобс',
        '"Единственный человек, кем ты должен стать - это человек, которого ты решаешь быть." — Ральф Уолдо Эмерсон',
        '"Не позволяй вчера забирать слишком много времени у сегодня." — Уилл Роджерс',
        '"Ты пропускаешь 100% бросков, которые не делаешь." — Уэйн Гретцки',
        '"Думаешь ли ты, что можешь, или не можешь - ты прав." — Генри Форд',
        '"Я понял, что смелость - это не отсутствие страха, а победа над ним." — Нельсон Мандела',
        '"Единственный способ достичь невозможного - верить, что это возможно." — Чарльз Кингслей',
        '"Успех - это не то, как высоко ты поднялся, а как ты заставляешь людей чувствовать себя рядом с тобой." — Зиг Зигляр',
        '"Делай то, что подсказывает твое сердце." — Элеонора Рузвельт',
        '"Единственное ограничение нашего понимания завтра - это сомнения в сегодня." — Франклин Д. Рузвельт',
        '"Обычно мы больше всего боимся делать именно то, что нам нужно." — Тим Ферриз',
        '"Не жди возможности. Создай ее." — Неизвестный',
        '"Мотивация приходит от работы над тем, что тебе дорого." — Неизвестный',
        '"Боль, которую ты чувствуешь сегодня, станет твоей силой завтра." — Неизвестный',
        '"Не нужно видеть всю лестницу, просто сделай первый шаг." — Мартин Лютер Кинг младший',
        '"Действуй так, как будто то, что ты делаешь, имеет значение. Потому что это так." — Уильям Джеймс',
        '"Успех - это путь от неудачи к неудаче без потери энтузиазма." — Уинстон Черчилль',
        '"Успешный воин - это обычный человек с лазерным фокусом." — Брюс Ли',
        '"Совершенство - это не место назначения; это непрерывный путь, который никогда не заканчивается." — Брайан Трейси',
        '"Не сдавайся. Страдай сейчас и живи остаток жизни как чемпион." — Мухаммед Али',
        '"Твое единственное ограничение - твоя душа." — Неизвестный',
        '"Держи глаза на цели." — Неизвестный',
        '"Сила приходит не из того, что ты можешь делать. Сила - это преодоление того, что ты думал, что не сможешь." — Рикки Роджерс',
        '"Мечтай. Желай. Делай." — Неизвестный',
        '"Успех не найдет тебя сам. Ты должен выйти и получить его." — Неизвестный',
        '"Чем больше ты работаешь для чего-то, тем большее удовлетворение ты чувствуешь, когда это достигаешь." — Неизвестный',
    ],
    'wisdom': [
        '"Единственная истинная мудрость в том, чтобы знать, что ты ничего не знаешь." — Сократ',
        '"В середине трудности кроется возможность." — Альберт Эйнштейн',
        '"Единственное, чего нам нечего бояться - это самого страха." — Франклин Д. Рузвельт',
        '"Жизнь, которую не осмыслили, не стоит жить." — Сократ',
        '"Познать себя - начало всей мудрости." — Аристотель',
        '"Величайшая слава в жизни не в том, чтобы никогда не упасть, а в том, чтобы каждый раз встать." — Нельсон Мандела',
        '"Мудрость - высшая часть счастья." — Софокл',
        '"Держать тело здоровым - наш долг, иначе мы не сможем сохранить ум сильным и ясным." — Будда',
        '"Единственный способ иметь дело со свободным миром - стать настолько абсолютно свободным, что твое существование - это акт восстания." — Альбер Камю',
        '"Ты не можешь научить человека ничему; ты можешь только помочь ему найти это в себе." — Галилей',
        '"Человек знания должен не только знать, что делать, но и воздерживаться от делания." — Конфуций',
        '"Мудрость - это не продукт образования, а результат пожизненных попыток приобрести ее." — Альберт Эйнштейн',
        '"Мудрые приспосабливаются к обстоятельствам, как вода принимает форму кувшина." — Китайская пословица',
        '"Все, что мы есть - результат того, о чем мы думали. Если человек говорит или действует со злой мыслью, его следует боль." — Будда',
        '"Мудрец извлекает больше пользы из врагов, чем глупец из друзей." — Балтасар Грасиан',
        '"Единственная истинная мудрость - признание своего невежества." — Сократ',
        '"Посадить сад - значит верить в завтра." — Одри Хепберн',
        '"Молчание - источник великой силы." — Лао-Цзы',
        '"Будь как вода." — Брюс Ли',
        '"Путешествие в тысячу миль начинается с одного шага." — Лао-Цзы',
        '"Все, что мы знаем о мудрости, неполно." — Сократ',
        '"Мы не можем жить только для себя. Тысяча волокон соединяет нас с другими людьми." — Герман Мелвилл',
        '"Мудрость - дочь опыта." — Леонардо да Винчи',
        '"Жизнь, которую не осмыслили, не стоит жить." — Сократ',
        '"Слова могут быть делами." — Джон Хейвуд',
        '"Каждый удар приближает меня к следующему хому-рану." — Бэйб Рут',
        '"Не ищи следовать по стопам мудрых; ищи того, что они искали." — Мацуо Басё',
        '"Чем больше ты знаешь, тем больше понимаешь, что не знаешь." — Неизвестный',
        '"Прими все в себе - действительно все. Ты - это ты, и это начало и конец." — Кларк Мустакас',
        '"Твое тело ведет точный учет твоих намерений." — Марта Грэм',
        '"Лучше молчать и казаться дураком, чем открыть рот и развеять все сомнения." — Неизвестный',
        '"Ум - это все. О чем ты думаешь, тем ты становишься." — Будда',
        '"Знание говорит, но мудрость слушает." — Джими Хендрикс',
        '"Кто контролирует прошлое - контролирует будущее. Кто контролирует настоящее - контролирует прошлое." — Джордж Оруэлл',
        '"В любом смысле семья - это связь с нашим прошлым, мост в наше будущее и связь друг с другом." — Алекс Хейли',
    ],
}

def append_quotes(filename: Path, quotes_list: list):
    """Append quotes to file, avoiding duplicates."""
    if filename.exists():
        existing = set(filename.read_text(encoding='utf-8').splitlines())
    else:
        existing = set()
    
    new_lines = [q for q in quotes_list if q not in existing]
    if new_lines:
        mode = 'a' if filename.exists() else 'w'
        with open(filename, mode, encoding='utf-8') as f:
            if filename.exists() and f.tell() > 0:
                f.write('\n')
            f.write('\n'.join(new_lines) + '\n')
        return len(new_lines)
    return 0


def main():
    total_added = 0
    print("Appending offline quotes with authors...\n")
    
    for theme in ['life', 'love', 'motivation', 'wisdom']:
        # English
        en_file = OUT_DIR / f'quotes_{theme}_en.txt'
        added_en = append_quotes(en_file, QUOTES_EN[theme])
        print(f"✅ {en_file.name}: +{added_en} quotes")
        total_added += added_en
        
        # Russian
        ru_file = OUT_DIR / f'quotes_{theme}.txt'
        added_ru = append_quotes(ru_file, QUOTES_RU[theme])
        print(f"✅ {ru_file.name}: +{added_ru} quotes")
        total_added += added_ru
    
    print(f"\n📊 Total quotes added: {total_added}")


if __name__ == '__main__':
    main()
